Implemented Login page
andrei-lastochkin-idf/jenkins_builder pull request #1
Opened 2022-03-16 10:39 UTC by andrei-lastochkin-idf

2022-03-16 11:11 UTC, dmitry-rachko-idf approved these changes

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf requested changes

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +                ErrorPlaceholder.LOGIN_INVALID, ErrorPlaceholder.PASSWORD_INVALID),
formatting - add a comma before the last closing bracket. flutter will format code prettier in this way

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/api_authorization_response.dart
> +  final String? color;
colour is a build status. so it's better to rename it into status and change type from string to enum with 2 states - success, failure. success=blue, failure=red

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_usecase.dart
> +      _cache.jobs = value?.data?.map((e) => Job.fromJson(e)).toList();
just fyi - (e) => Job.fromJson(e) can be changed to Job::fromJson or smith like this. press option+enter and identify will suggest u

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_usecase.dart
> +        base64.encode(utf8.encode(params.login! + ':' + params.password!));
better to work with default values (params.login ?? '') instead of force unwrap

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +  bool _isLoading = false;
isLoading can be moved into BaseBlocImpl, in this case u won't specify it in each bloc

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    );
it's a good practice to separate mapping. creating new model from screenData fields is also mapping. so u can create separate class LoginViewMapper, create map function here. for example, mapScreenDataToLoginRequest and have object creation logic here. and then pass the mapper object to bloc via di

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +      await _loginUseCase(loginFields).then(
don't forget to add validation

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    try {
u can change it to launchPayload as I showed u

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +                    return screenData.exception?.passwordError;
not the needed variant - try to resolve the issue with validation from bloc

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +            }
what is this?

2022-03-23 17:23 UTC, sergei-mikhailovskii-idf commented on packages/presentation/pubspec.yaml
>      path: ../domain
no need in domain here. data contains it already

2022-03-25 15:24 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/login_usecase.dart
> +      _cache.jobs = value?.data?.map((e) => Job.fromJson(e)).toList();
unfortunately, I did not find the solution

2022-03-25 17:03 UTC, sergei-mikhailovskii-idf requested changes

2022-03-25 17:03 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +      _LoginBloc(loginUseCase, loginValidationUseCase, loginViewMapper);
formatting

2022-03-25 17:03 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +      this._loginUseCase, this._loginValidationUseCase, this._loginViewMapper);
formatting

2022-03-25 17:03 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +              'Login',
localization

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf requested changes

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +              "password.invalid",
create a separate file where u'll keep such errors. maybe they will duplicate so it'd be easier to use them as variables

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/utils/api_path.dart
> +}
formatting

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/validator/min_length_validator.dart
> +          "Class $runtimeType, method isValid. ${field.runtimeType} is not String");
comma

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/validator/regexp_validator.dart
> +          "Class $runtimeType, method isValid. ${field.runtimeType} is not String");
-//-

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/validator/required_field_validator.dart
> +          "Class $runtimeType, method isValid. ${field.runtimeType} is not String");
-//-

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/mapper/error_mapper.dart
> +  static String? mapErrorToMessage(BuildContext context, String? errorKey) {
remove static, pass mapper via di

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/mapper/error_mapper.dart
> +        return AppLocalizations.of(context)!.requiredField;
declare AppLocalizations.of(context)! as separate variable

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/app/app.dart
> +import 'package:flutter/material.dart';
why do u have application and app classes? keep one of them and remove other

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +          LoginViewMapper loginViewMapper) =>
comma

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +        passwordFieldKey.currentState?.validate();
why do u validate fields while login click?

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +          _loginViewMapper.mapScreenDataToRequest(_screenData),
move it to separate variable

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    super.handleData(
add validating fields to update data, it will help u to duplicate writing validate (in onChange and login for ex)

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    if (_screenData.exception?.loginError != null) {
no need in this condition. make loginError null always, it's not a problem. it's also not a problem to call update data each time. so u'll have the following logic:

_screenData.exception?.loginError = null;
_screenData.loginInput = login;
updateData();

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +  void updateData() {
make it private

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    _screenData.passwordInput = password;
-//-

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +                AppLocalizations.of(context)!.labelPassword,
try to move AppLocalizations.of(context)! to base class. seems that it's possible

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +                    context, screenData.exception?.passwordError),
static -> di + comma

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +              child: TextFormField(
create AppTextFormField for example. it'll be a stateful widget that returns TextFormField. it will help u to avoid defining styles everywhere

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +                    context, screenData.exception?.loginError),
comma

2022-03-28 09:18 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login.dart
> +                      ),
create separate file styles. place here the variable/method roboto18W500WhiteStyle. and use it everywhere

2022-03-28 11:30 UTC, andrei-lastochkin-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +    if (_screenData.exception?.loginError != null) {
I'm using this condition to clear an error state when onChanged triggers for the first time after user got this error. In my point there is no need to call validate() each time the field is changed

2022-03-28 11:33 UTC, andrei-lastochkin-idf commented on packages/presentation/lib/screen/login/bloc/login_bloc.dart
> +        passwordFieldKey.currentState?.validate();
I set exception to null and use validate() fields to clear error state of them while progress indicator is running

2022-03-28 12:54 UTC, sergei-mikhailovskii-idf approved these changes

2022-03-28 13:04 UTC, merged