Implemented Home Page
andrei-lastochkin-idf/jenkins_builder pull request #3
Opened 2022-04-05 16:47 UTC by andrei-lastochkin-idf

Added: 
Splash screen,
dynamic tabs,
logic for primaryView definition,
crashlytics and analytics.

2022-04-06 11:20 UTC, dmitry-rachko-idf approved these changes
all is well in my humble opinion)

2022-04-06 11:30 UTC, dmitry-rachko-idf commented on packages/data/lib/repository/local_storage_repository.dart
> +    final prefs = await SharedPreferences.getInstance();
provide shared prefs via di

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf requested changes

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/dio/dio_builder.dart
> +    GetIt.I.get<TokenInterceptor>(),
pass it as a param and get from container in the injector file

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/dio/token_interceptor.dart
> +      RequestOptions options, RequestInterceptorHandler handler) async {
formatting

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/local_storage_repository.dart
> +  Future<String?> getToken() async => _prefs.getString("token");
define key "token" as a const here and use it

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +          path: url + 'api/json',
move api/json to constant in separate class, like PathHelper

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/api_authorization_response.dart
> +class View {
(optional) rename View to JobsView, as View seems as smth from ui

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_primary_view_usecase.dart
> +      _cache.views?.indexWhere(
indexWhere returns -1 if it doesn't find anything, not null. think about it

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_token_usecase.dart
> +class GetTokenUseCase implements UseCase<Future<bool>> {
as use case returns bool, it seems that it's not GetTokenUseCase, but HasTokenUseCase. just naming difference, yes

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_token_usecase.dart
> +        : Future.value(true);
seems prettier:

```
final hasToken = await _repository.getToken() != null
return Future.value(hasToken)
```

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_views_usecase.dart
> +              .reversed
reverse -> shifting

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_views_usecase.dart
> +          _cache.jobs = response?.jobData?.map((e) => Job.fromJson(e)).toList();
.map(Job.fromJson)

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/home_usecase.dart
> +                response?.jobData?.map((e) => Job.fromJson(e)).toList();
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/home_usecase.dart
> +      final view = _cache.views?.firstWhere(
maybe firstWhereOrNull?

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/home_usecase.dart
> +      return await _repository.getJobsByView(view!.url!).then(
! -> ?

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/home_usecase.dart
> +                response?.jobData?.map((e) => Job.fromJson(e)).toList(),
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_usecase.dart
> +      _cache.jobs = response?.jobData?.map((e) => Job.fromJson(e)).toList();
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/di/injector.dart
> +    () => RootBloc(
(optional) RootBloc -> MainBloc (as it's main screen)

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/internal/analytics_service.dart
> +      {required String event, Map<String, Object?>? parameters});
formatting

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/mapper/color_mapper.dart
> +  static Color getColorByName(String? color) {
remove static, add di

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/mapper/root_view_mapper.dart
> +        (view) => HomePage(view: view.name!),
! -> ?

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/mapper/root_view_mapper.dart
> +          title: view.name?.toUpperCase() ?? "",
try to create an extension for String, call it orEmpty. the field/method will return string like that:

return value ?? "" (if field - add it to getter)

it would be prettier, if in code u'll have such construction view.name?.toUpperCase().orEmpty

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/home.dart
> +            itemCount: screenData.jobs!.length,
! -> ?

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/home.dart
> +                job: screenData.jobs![index],
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/home.dart
> +                child: Text("Сорян, ничего не нашли",
localization

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/home.dart
> +                    style: textStyles.nunito22W700Gray),
formatting

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/home.dart
> +                if (screenData.jobs!.isEmpty) {
! -> ?

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/root/bloc/root_bloc.dart
> +      event: "${tabName}_tab_clicked",
create separate file for analytics events

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash/bloc/splash_bloc.dart
> +      _analyticsService.trackCustomEvent(event: "home_screen_opened");
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash/bloc/splash_bloc.dart
> +      _analyticsService.trackCustomEvent(event: "login_screen_opened");
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash/splash.dart
> +              "JenkinsApp",
localization

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash/splash.dart
> +              "App for building something great",
-//-

2022-04-07 09:20 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/widget/job_card.dart
> +  final Job job;
pass here not job model, but string jobname and mapped jobcolor. the view should be as simple as it can be. no mappings here. and also it should be reusable. so it's better to avoid passing whole models here. pass fields

2022-04-07 15:04 UTC, andrei-lastochkin-idf commented on android/app/build.gradle
> +        minSdkVersion 24
I set it to 19 as required by firebase_analytics plugin

2022-04-08 09:05 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/get_views_usecase.dart
> +          _cache.jobs = response?.jobData?.map((e) => Job.fromJson(e)).toList();
Unfortunately I couldn't find any solution
https://stackoverflow.com/questions/56773013/can-i-have-lambda-expression-that-simply-gets-object-property-in-dart2

2022-04-08 09:05 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/home_usecase.dart
> +                response?.jobData?.map((e) => Job.fromJson(e)).toList();
-//-

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf approved these changes

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_views_usecase.dart
> +    return views;
?

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/di/injector.dart
>  import 'package:domain/usecase/get_primary_view_usecase.dart';
order

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/home/bloc/home_bloc.dart
> +    _screenData.jobs = await _homeUseCase(view ?? '');
u can use orEmpty here

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/main/bloc/main_bloc.dart
> +    _screenData.primaryViewIndex = _getPrimaryViewUseCase() ?? 0;
move null check to usecase

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/main/bloc/main_bloc.dart
> +    );
concatenate value in AnalyticsEvent, like _analyticsEvent.getTabAnalyticsName(tab)

2022-04-08 13:26 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash/bloc/splash_bloc.dart
> +import 'package:domain/usecase/has_token_usecase.dart';
order

2022-04-08 14:13 UTC, merged